#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import numpy as np
from numba import njit
import sisl
import sys
import os

options = {'file':'None',
           'delete_if_wrong':'False',
           'dcut':'1.6',
           'remove_duplicates':'False',
           'numba_cache': 'False',
           'ase_visualize':'False',
           'no_hydrogen':'False',
           }

os.chdir(os.getcwd())

argv = sys.argv[1:]
for a in argv:
    if len(a.split('='))>2:
        print(a)
        k,w = a.split('=')[0],'='.join(a.split('=')[1:])
    else:
        k,w = a.split('=')
    options.update({k:w})

print('Checking ' + options['file'], ' located at ', os.getcwd())
geom = sisl.get_sile(options['file']).read_geometry()
xyz  = geom.xyz.copy()
lat  = geom.cell.copy()
s    = geom.atoms.Z.copy()
dcut = float(options['dcut'])
#print(lat)
if options['ase_visualize'] =='True':
    from ase.visualize import view
    view(geom.toASE())



@njit(cache=True if options['numba_cache']=='True' else False)
def Check_Distances(xyz,s, cell, no_hydrogen):
    n = len(xyz)
    no_hyd = True if no_hydrogen=='True' else False
    TF = True
    C1,C2 = cell[0:2]
    for i in range(n):
        nn_count  = 0
        dub_count = 0
        for r1 in range(-1,2):
            for r2 in range(-1,2):
                dij = np.sum(((xyz[i] + r1*C1 +r2*C2) - xyz)**2, axis=1)**0.5
                nn_count  += sum((dij < dcut) * (dij > 0.1))
                dub_count += sum(dij  < 0.1)
        
        if nn_count !=3 and s[i]==6:
            TF = False
            if nn_count == 2  and no_hyd == False:
                print('Warning: Carbon ', i, ' has suspicious number of neighbors. It has ', nn_count,'.')
            elif nn_count!=2:
                print('WARNING: Carbon ', i, ' has suspicious number of neighbors. It has ', nn_count,'.')
        if nn_count == 2 and no_hyd:
            TF = True
        
        if nn_count !=1 and s[i]==1:
            TF = False
            print('WARNING: Hydrogen ', i, ' has suspicious number of neighbors. It has ', nn_count,'.')
        
        if dub_count != 1:
            TF = False
            print('Atom ', i, ' has duplicate')
    
    return TF

TF = Check_Distances(xyz, s, lat, options['no_hydrogen'])
if TF:
    print('All Good')
    exit()

if options['delete_if_wrong'] == 'True':
    os.system('rm '+options['file'])
    
if options['remove_duplicates'] == 'True':
    na = geom.na
    # go backwards in the atoms and check for duplicates
    for i in range(na, -1, -1):
        if len(geom.close(i,R=[0.1]))>1:
            geom = geom.remove([i])
    
    print('Overwriting file with duplicates')
    geom.write(options['file'])
    
    


        

    




